context:
  version: "0.4.3"
  python_min: 3.12

package:
  name: moutils
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/m/moutils/moutils-${{ version }}.tar.gz
    sha256: 919f5b2ec2796c5a01a549b3d4cc26c22fef2ec3332820a164b45bfc9a9ce35a

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - anywidget >=0.9.0
    - requests >=2.0.0

tests:
  - python:
      imports:
        - moutils
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/marimo-team/moutils
  documentation: https://marimo-team.github.io/moutils/
  summary: Utility functions used in marimo.
  license: MIT
  license_file: LICENSE
  description: |
    A collection of utility widgets designed for browser interaction, including URL manipulation, DOM querying, cookie management, storage access, clipboard operations, and an interactive shell for running terminal commands.

extra:
  recipe-maintainers:
    - claudiushaag
